export const s = {
  panel: {
    width: "100%",
    height: "100%",
    background: "#121212",
    borderRight: "1px solid #202024",
    display: "flex",
    flexDirection: "column" as const,
    flexShrink: 0,
    overflow: "hidden",
  },
  header: {
    height: 38,
    padding: "0 12px 0 14px",
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 600,
    color: "#f0f0f1",
    borderBottom: "1px solid #202024",
    flexShrink: 0,
    overflow: "hidden",
  },
  title: {
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  headerBtn: {
    width: 22,
    height: 22,
    borderRadius: 6,
    color: "#9b9ba1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  search: {
    height: 40,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 14px",
    color: "#717178",
    borderBottom: "1px solid #171719",
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    background: "transparent",
    color: "#d6d6d8",
    outline: "none",
    fontSize: 13,
  },
  tabs: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 2,
    padding: "6px 8px",
    background: "#121212",
  },
  tab: {
    height: 27,
    borderRadius: 7,
    color: "#bdbdc1",
    fontSize: 12,
    background: "transparent",
    boxShadow: "none",
  },
  tabActive: {
    background: "#303033",
    color: "#f5f5f6",
    boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.08), 0 1px 2px rgba(0,0,0,0.5)",
  },
  tree: {
    flex: 1,
    overflow: "auto",
    padding: "4px 6px 12px",
    scrollbarWidth: "thin" as const,
    scrollbarColor: "#1a1a1a transparent",
  },
  studioPane: {
    flex: 1,
    overflow: "auto",
    padding: "4px 6px 12px",
    scrollbarWidth: "thin" as const,
    scrollbarColor: "#1a1a1a transparent",
  },
  designPane: {
    flex: 1,
    display: "flex",
    minHeight: 0,
    overflow: "hidden",
    padding: "4px 6px 12px",
    scrollbarWidth: "thin" as const,
    scrollbarColor: "#1a1a1a transparent",
  },
  studioEmpty: {
    borderTop: "1px solid #202024",
    paddingTop: 12,
    color: "#a5a5ab",
  },
  studioHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 10,
  },
  studioKicker: {
    fontSize: 13,
    fontWeight: 600,
    color: "#d8d8dc",
  },
  studioAddBtn: {
    width: 22,
    height: 22,
    border: "none",
    borderRadius: 6,
    background: "transparent",
    color: "#96969d",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  studioInput: {
    width: "100%",
    height: 28,
    boxSizing: "border-box" as const,
    border: "1px solid #2a2a2e",
    borderRadius: 6,
    background: "#171719",
    color: "#dedee2",
    outline: "none",
    padding: "0 8px",
    fontSize: 12,
    marginBottom: 8,
  },
  studioList: {
    display: "flex",
    flexDirection: "column" as const,
  },
  studioNote: {
    minHeight: 28,
    border: "none",
    borderRadius: 6,
    background: "transparent",
    color: "#bdbdc1",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "4px 6px",
    cursor: "pointer",
    textAlign: "left" as const,
  },
  studioNoteTitle: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 13,
  },
  studioNoteDate: {
    flexShrink: 0,
    color: "#77777f",
    fontSize: 11,
  },
  memberItem: {
    minHeight: 32,
    border: "none",
    borderRadius: 6,
    background: "transparent",
    color: "#bdbdc1",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "4px 6px",
    cursor: "default",
    textAlign: "left" as const,
    fontSize: 13,
  },
  memberStatus: {
    width: 7,
    height: 7,
    borderRadius: 99,
    flexShrink: 0,
  },
  memberAvatar: {
    width: 20,
    height: 20,
    borderRadius: 5,
    background: "#7c5cbf",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    fontWeight: 700,
    flexShrink: 0,
  },
  studioText: {
    fontSize: 13,
    lineHeight: 1.45,
    color: "#85858c",
  },
  item: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    minHeight: 26,
    padding: "3px 7px",
    cursor: "pointer",
    fontSize: 13,
    color: "#b9b9be",
    whiteSpace: "nowrap" as const,
    border: "none",
    background: "transparent",
    width: "100%",
    textAlign: "left" as const,
    boxSizing: "border-box" as const,
    borderRadius: 6,
  },
  icon: {
    width: 15,
    height: 15,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#a6a6aa",
  },
  label: { overflow: "hidden", textOverflow: "ellipsis", flex: 1 },
  badge: {
    minWidth: 12,
    padding: "0 1px",
    color: "#8a8a91",
    fontSize: 11,
    fontWeight: 600,
    textAlign: "right" as const,
  },
  branch: {
    position: "absolute" as const,
    left: 17,
    top: -4,
    bottom: -4,
    width: 1,
    background: "#252529",
  },
  spinner: {
    width: 12,
    height: 12,
    border: "2px solid var(--border-weaker-base)",
    borderTopColor: "var(--text-weak)",
    borderRadius: "50%",
    animation: "spin 0.6s linear infinite",
  },
  contextMenu: {
    position: "fixed" as const,
    zIndex: 200,
    background: "#141414",
    border: "1px solid var(--border-weak-base)",
    borderRadius: "var(--radius-md)",
    boxShadow: "var(--shadow-lg)",
    padding: "4px 0",
    display: "flex",
    flexDirection: "column" as const,
  },
  menuItem: {
    padding: "6px 10px",
    fontSize: "var(--font-size-small)",
    color: "var(--text-base)",
    cursor: "pointer",
    border: "none",
    background: "transparent",
    textAlign: "left" as const,
    fontFamily: "var(--font-family-sans)",
    whiteSpace: "nowrap" as const,
  },
  menuSep: { height: 1, background: "var(--border-weaker-base)", margin: "4px 0" },
  errorBar: {
    padding: "4px 8px",
    fontSize: "var(--font-size-small)",
    color: "var(--text-on-critical-base)",
    background: "var(--surface-critical-base)",
  },
  dropHighlight: {
    outline: "2px solid var(--button-primary-base)",
    outlineOffset: -2,
    borderRadius: "var(--radius-sm)",
  },
};
