export const s = {
  container: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    height: "100%",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 12px",
    height: 34,
    borderBottom: "1px solid var(--border-weaker-base)",
    flexShrink: 0,
  },
  fileName: {
    fontSize: "var(--font-size-small)",
    color: "var(--text-strong)",
    fontWeight: 500,
  },
  filePath: {
    fontSize: "var(--font-size-small)",
    color: "var(--text-weaker)",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  editor: {
    flex: 1,
    overflow: "hidden",
    background: "transparent",
  },
  error: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-weaker)",
    fontSize: "var(--font-size-small)",
  },
  backBtn: {
    border: "none",
    background: "transparent",
    color: "var(--icon-base)",
    cursor: "pointer",
    padding: "2px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "var(--radius-sm)",
  },
  saveBtn: {
    padding: "3px 10px",
    borderRadius: "var(--radius-md)",
    border: "none",
    background: "var(--button-primary-base)",
    color: "var(--background-base)",
    fontSize: "var(--font-size-small)",
    cursor: "pointer",
    fontWeight: 500,
  },
};
